### PR TITLE
set owner of `app/bootstrap/cache` to `www-data` after `composer install`

### PR DESCRIPTION
**Pull request by yinshanyang**

### CODE REVIEW

**Comment by lalop** [comment]
Hi @yinshanyang ,
Can you explain what error this will solve please ?

**Comment by yinshanyang** [comment]
without setting ownership, if I try to setup a fresh install, I get this error:

```
ErrorException in ClassPreloader.php line 87:
fopen(/var/www/app/bootstrap/cache/compiled.php): failed to open stream: Permission denied
```

after submitting the initial setup form:

screen shot 2016-04-20 at 2 47 59 pm

**Comment by lalop** [comment]
Thank you for your pr

**Comment by yinshanyang** [comment]
no worries

**Pull request merged**
