### PR TITLE
Added install-php-extensions

### PR DESCRIPTION
**Pull request by lwj5**
Hi,

I've added https://github.com/mlocati/docker-php-extension-installer to help automate the dependency management for PHP extensions, most extension can be installed by using `install-php-extensions`. Now all the `apk add` packages are solely for IN, which makes it easier for you to track.

No changes to PHP extensions were made.

Also, I made PHP's php.ini-production as the default php.ini, and use the php.ini in this repo to overwrite the default values instead.

Cheers.

### CODE REVIEW

**Comment by hillelcoren** [comment]
You rock, thank you!

**Comment by turbo124** [comment]
@lwj5 thank you for this!

Is there any reason why the mbstring package was removed?

**Comment by lwj5** [comment]
Yes, I should clarified. They come with php-fpm. 

install-php-extension warned that these 3 ext were already installed.
iconv 
mbstring
pdo

**Comment by lwj5** [comment]
Also let me know if there’s any plans on your side to develop a helm chart for IN. The helm chart helps to deploy all the modules into Kubernetes easily.

If not, let me know if you are ok if I were to develop one in my free time and share it. No ETA yet

**Comment by turbo124** [comment]
@lwj5 thanks for the PR, it is appreciated!

In regards to helm charts, yes!! we would like to expand our footprint for kubernetes deployments.

If you want to chat direct, please join our slack https://slack.invoiceninja.com to discuss further.

**Pull request merged**
