### PR TITLE
[add] mysql performance improvement

### PR DESCRIPTION
**Pull request by AurelienLavorel**
Use docker volume to improve performance.

### CODE REVIEW

**Comment by lalop** [comment]
can't we use docker's volume for invoiceninja's container too ?

**Comment by AurelienLavorel** [comment]
Yes we can but it'll be harder to see logs from docker host.

**Comment by lalop** [comment]
thank you

**Comment by pierreozoux** [comment]
@AurelienLavorel what do you mean? Ah you men logs are in data folder?
grr :) stdout/stderr FTW \o/

But yes, agree with @lalop if we do it, then, let's do it for both.

**Comment by AurelienLavorel** [comment]
Yeah I know, I'm not talking about access log.
`ls srv/invoiceninja/storage/logs/`
- failed-logins.log
- stacktrace.log

**Comment by lalop** [comment]
humm, that 's embarassing this to log have their on logs wirter, they are ignoring the log setting https://github.com/invoiceninja/invoiceninja/blob/master/.env.example#L32
@hillelcoren can we make something for that ? Maybe log all in the error log with kind of label `[failed-login] ...` , `[stacktrace] ... `  ...

**Comment by hillelcoren** [comment]
This is by design. Most people aren't using tools to analyze their logs, separating out the failed logins and stacktrace details makes it easier to see the login attempts and easier to read the errors in the logs.

That said we can support both behaviors, I'll look into it...

**Comment by hillelcoren** [comment]
I understand the desire to keep the logs organized but I'm reluctant to change the format for existing users. Having the errors separated out makes debugging a lot easier for us. 

With that in mind... I've checked in a change to ensure the app respects the log setting for all but single. The other options are: daily, syslog, and errorlog.

**Pull request merged**
