### PR TITLE
Clear the .env file on every startup

### PR DESCRIPTION
**Pull request by cinemast**
Currently the variables get appended to the file each time there is a restart. This commit fixes this issue.

### CODE REVIEW

**Comment by lalop** [comment]
This may have some unwanted effect.
I have to make some test before merge it

**Comment by freskimo** [comment]
Actually writing the .env file is duplicate. In Laravel when the env variables are set, they automatically are loaded. No need for this extra .env file...

This also eliminates your problem @cinemast

**Comment by lalop** [comment]
@freskimo yes you are right, writing to `.env` from the entrypoint could be usefull only for mysql automatic detection variable

**Comment by cinemast** [comment]
I overlooked that completly. @freskimo is right. Removing this file could also avoid misunderstandings such as this one.

**Comment by freskimo** [comment]
I made a PR with the fix: https://github.com/invoiceninja/dockerfiles/pull/40

**Comment by cinemast** [comment]
closing this in favor of #40

**Pull request closed without merging**
