### PR TITLE
DB init mechanism

### PR DESCRIPTION
**Pull request by freskimo**
Added doc and small changes to the app-entrypoint to allow initializing the db through commandline instead of using the web installer.

in response of https://github.com/invoiceninja/dockerfiles/issues/42

### CODE REVIEW

**Comment by lalop** [comment]
Why don't just add some instructions in the Readme to explain what to do to init the database :

```
docker run -it --rm invoiceninja/invoiceninja php artisan optimize --force
docker run -it --rm invoiceninja/invoiceninja php artisan migrate --seed --force
```

**Comment by lalop** [comment]
And the same for update

**Comment by freskimo** [comment]
Well you are right this only a small improvement for the UX. But in this way the user is not bothered with the internal structure and framework of the application. 

We can add more cmds in the future like interactive installation via commandline, update, activate license, clear cache, full backup db + storage, change app key + db in case of a breach, ...

**Comment by lalop** [comment]
Sorry but I prefer to refer to invoiceninja command then wrapping them

**Pull request closed without merging**
