### PR TITLE
[BUGFIX] Error building the mysql backup build

### PR DESCRIPTION
**Pull request by Psycho0verload**
Bugfix for #452 
Change MYSQL5 to MYSQL5-Debian so that build works for the backup cronjob.
I have implemented this in a running system and the migration worked without problems

### CODE REVIEW

**Comment by Psycho0verload** [comment]
Add Fix for #454

**Comment by turbo124** [comment]
Thanks!

**Comment by almereyda** [comment]
For the fix for #454, I'd suggest not to use quotes around the asterisk, if not necessary. Docker Compose will interpret them literally, when read from an `env` file. Also see https://docs.docker.com/compose/compose-file/#env_file-format

**Comment by maejok-xx** [comment]
Was there ever a solution for this? It's still an issue almost a year later.

It looks like from the previous comments the `mysql:8-debian` image is not compatible...is that correct?

**Pull request merged**
