### PR TITLE
Update Readme.md - missing sudo

### PR DESCRIPTION
**Pull request by manakill**
without sudo response is "chmod: changing permissions of 'docker/app/public': Operation not permitted"

### CODE REVIEW

**Comment by lwj5** [comment]
Why do you need sudo?

shouldn’t the files and folders be owned by you will you first pull or download them?

**Comment by manakill** [comment]
The Docker directions say:
From the terminal run

chmod 755 docker/app/public
sudo chown -R 1500:1500 docker/app


And with those directions you get the error as stated above. Cannot complete directions otherwise.

**Comment by lwj5** [comment]
Shouldn’t the files and folders be owned by you will you first pull or download them? You don’t need sudo to chmod files you own

**Comment by manakill** [comment]
These questions you are asking, could be answered by looking at the Docker directions, or running real testing on physical R Pi 4 ARM64 like I have done. 

Directions Say:
git clone https://github.com/invoiceninja/dockerfiles.git
cd dockerfiles
then edit env and docker-compose.yml
then sudo commands

Raspian(default Pi OS) has the default user with no privileges - hence sudo is required

**Comment by manakill** [comment]
A separate Raspberry Pi 4 (ARMv7 and ARM64) installation instructions could be helpful than to mix the directions in together.

**Comment by lwj5** [comment]
@tacticz would you be able to comment on this? Did you face the same issue

**Pull request closed without merging**
