### PR TITLE
Correct timezone in container needed, added tzdata package to respect timezone via `TZ` Env Variable

### PR DESCRIPTION
**Pull request by alexanderhofstaetter**

### CODE REVIEW

**Comment by alexanderhofstaetter** [comment]
#397

**Comment by turbo124** [comment]
The app does all its calculations in UTC +0, changing to a different timezone may impact a lot of calculations inside the app.

**Comment by turbo124** [comment]
@lwj5 do you agree we should keep the container @ UTC?

**Comment by lwj5** [comment]
@alexanderhofstaetter is there any specific use case, that you require setting timezone in the docker container?

**Pull request closed without merging**
