### PR TITLE
Build on ARM64

### PR DESCRIPTION
**Pull request by lwj5**

### CODE REVIEW

**Comment by tacticz** [comment]
Hello @lwj5,

First of all thank you for integrating the ARM64 build in the official docker image. I can confirm it is working on my RasPi 4!
 
In issue #183 you asked me whether I could help with the ARM64 version, and I told you I'd be glad to help, so here is my feedback:

Although **the dockerhub's invoiceninja/invoiceninja:5 image is now running on ARM64**, the current `docker-compose.yml` file is still using:
```
  db:
    image: mysql:5
```
Which, as explained under the **Modifying docker-compose.yml** section of [my post](https://github.com/invoiceninja/dockerfiles/issues/183#issuecomment-807280903) , **is NOT ARM64 compatible**, and outputs the following message when issuing `docker-compose up -d`:
```
5: Pulling from library/mysql
docker: no matching manifest for linux/arm64/v8 in the manifest list entries.
```

I had to change the image reference to:
```
  db:
    image: mariadb:10.4
```
Which **is ARM64 compatible** in order to be able to launch all 3 containers on the RasPi.

Maybe you could update the `docker-compose.yml` as follow to make things easy for people willing to deploy on ARM64:
```
  db:
    image: mysql:5
    # Use MariaDB when running on ARM64
    #image: mariadb:10.4
```
Hope this can help.

**Comment by lwj5** [comment]
Thanks @tacticz! Good to hear. Can I check if the env for mariadb remains the same as mysql?

**Comment by tacticz** [comment]
Absolutely!
I've checked both [MySQL](https://hub.docker.com/_/mysql)'s and [MariaDB](https://hub.docker.com/_/mariadb)'s dockerhub pages and I can confirm that both **Environment Variables** and **Docker Secrets** sections are a copy/paste of each others with only the term `mysql` replaced by `mariadb`.

The **only exception** being the **`MYSQL_ONETIME_PASSWORD`** which is **not available in MariaDB**.
> Sets root (not the user specified in MYSQL_USER!) user as expired once init is complete, forcing a password change on first login. Any non-empty value will activate this setting. NOTE: This feature is supported on MySQL 5.6+ only. Using this option on MySQL 5.5 will throw an appropriate error during initialization.

Which means that **environment variables set for MySQL can be reused _as is_ for MariaDB configuration**.

**Comment by lwj5** [comment]
Thanks @tacticz for the info. 

I won’t be able to work on it this week. I’ll try to get on it the following week.

**Comment by turbo124** [comment]
@tacticz if you PR your changes we can merge that in :)

**Pull request merged**
