### PR TITLE
Enable additional SMTP env variables

### PR DESCRIPTION
**Pull request by cinemast**

### CODE REVIEW

**Comment by lalop** [comment]
thank you

**Comment by lalop** [comment]
@cinemastn, why don't use the same varaible name ?
```
MAIL_FROM_NAME=$SMTP_FROM_NAME
```

instead of
```
MAIL_FROM_NAME=$MAIL_FROM_NAME
```

**Comment by cinemast** [comment]
Actually no reason, feel free to change it. This is just how I defined it for my environment.

**Comment by lalop** [comment]
I changed it

**Comment by cinemast** [comment]
Thank you, of course this makes much more sense.

**Pull request merged**
