### PR TITLE
Set trusted proxy value to allow invoiceninja to read nginx headers

### LINKED ISSUE #355: "View PDF" in Invoice section redirects to HTTP URL
**What version of Invoice Ninja are you running? ie v4.5.25 / v5.0.30**
v5.1.65

**What environment are you running?**
Docker/Helm

**Have you checked log files (storage/logs/) Please provide redacted output**
None, see screenshot below and info reported by @ffaen https://github.com/invoiceninja/dockerfiles/issues/349#issuecomment-846222887

**Have you searched existing issues?**
Yes

**Have you reported this to Slack/forum before posting?**
No

**Describe the bug**
Clicking "View PDF" in an invoice section redirects to HTTP URL. Leading to a `blocked:mixed content` by Chrome.
Although APP_URL is using HTTPS.

Unfortunately, I haven't had time to look into the code, so I can't say what is wrong yet.

**Steps To Reproduce**
- Launch a fresh instance of IN (helm in this case)
- Use https://xxx as APP_URL
- Create an invoice
- Click "View PDF"

**Expected behavior**
The download is redirected to an HTTPS URL

**Screenshots**
Screenshot 2021-05-24 at 12 23 16 AM

After allowing mixed content in Chrome:
Screenshot 2021-05-24 at 12 05 41 AM

Note: 2nd redirect is due to my server rule settings redirecting all HTTP traffic to HTTPS

**Additional context**
TLS terminates at the load balancer
See network topology here: https://github.com/invoiceninja/dockerfiles/issues/349#issuecomment-841840164

Note: Before posting don't forget to check our "Troubleshooting" category in the [docs](https://invoiceninja.github.io/docs/self-host-troubleshooting/) (https://invoiceninja.github.io/docs/self-host-troubleshooting/).

**(v5) Can you replicate the issue on our demo site? https://demo.invoiceninja.com**
No

### PR DESCRIPTION
**Pull request by ffaen**
Fixes #355

### CODE REVIEW

**Comment by ffaen** [comment]
CI Failed because I haven't bumped the version, not sure if this is something that you would like to do, or if you prefer me bump it in the PR?

**Comment by lwj5** [comment]
Yes, please go ahead and bump the version to 0.5.1.

Also, do add trustedProxy parameter to the README.md.

**Comment by ffaen** [comment]
Ping @lwj5, not sure if you get notified when there are new commits

**Comment by lwj5** [comment]
Thanks @ffaen! Yes you are right no notifications for commits :(

**Pull request merged**
